spring:
  config:
    activate:
      on-profile: dev

  # JPA
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

# 로그 레벨
logging:
  level:
    com.loopon: INFO
    org.hibernate.SQL: INFO

loopon:
  server:
    url: https://api.loopon.cloud

# APNS
apns:
  environment: sandbox
